Rails:
  Enabled: true

# v0.48.0 に `||` でエラーになるバグがあるため。 pull/4175
Rails/Blank:
  Enabled: false

# slug とか created_by とか、NOT NULL だが create_table 時に
# default 値を定義できないカラムは存在する。
Rails/NotNullColumn:
  Enabled: false

# method_missing を隠したい場合は respond_to? を使うべき
Rails/SafeNavigation:
  ConvertTry: true

# valid? チェックし忘れを防ぎたい
Rails/SaveBang:
  Enabled: true
